// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "customer": customer Resource Client
//
// Command:
// $ goagen
// --design=github.com/gostore/src/customer/design
// --out=$(GOPATH)/src/github.com/gostore/src/customer
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListCustomerPath computes a request path to the list action of customer.
func ListCustomerPath() string {

	return fmt.Sprintf("/customers/")
}

// Lists all customers
func (c *Client) ListCustomer(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewListCustomerRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListCustomerRequest create the request corresponding to the list action endpoint of the customer resource.
func (c *Client) NewListCustomerRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowCustomerPath computes a request path to the show action of customer.
func ShowCustomerPath(customerID int) string {
	param0 := strconv.Itoa(customerID)

	return fmt.Sprintf("/customers/%s", param0)
}

// Get customer by id
func (c *Client) ShowCustomer(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowCustomerRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowCustomerRequest create the request corresponding to the show action endpoint of the customer resource.
func (c *Client) NewShowCustomerRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
