// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "customer": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/gostore/src/customer/design
// --out=$(GOPATH)/src/github.com/gostore/src/customer
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
	"strconv"
)

// ListCustomerContext provides the customer list action context.
type ListCustomerContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListCustomerContext parses the incoming request URL and body, performs validations and creates the
// context used by the customer controller list action.
func NewListCustomerContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListCustomerContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListCustomerContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListCustomerContext) OK(r *GoaExampleCustomer) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.customer+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ListCustomerContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}

// ShowCustomerContext provides the customer show action context.
type ShowCustomerContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	CustomerID int
}

// NewShowCustomerContext parses the incoming request URL and body, performs validations and creates the
// context used by the customer controller show action.
func NewShowCustomerContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowCustomerContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowCustomerContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramCustomerID := req.Params["customerID"]
	if len(paramCustomerID) > 0 {
		rawCustomerID := paramCustomerID[0]
		if customerID, err2 := strconv.Atoi(rawCustomerID); err2 == nil {
			rctx.CustomerID = customerID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("customerID", rawCustomerID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowCustomerContext) OK(r *GoaExampleCustomer) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.example.customer+json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowCustomerContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}
