// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "customer": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/gostore/src/customer/design
// --out=$(GOPATH)/src/github.com/gostore/src/customer
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// CustomerHref returns the resource href.
func CustomerHref(customerID interface{}) string {
	paramcustomerID := strings.TrimLeftFunc(fmt.Sprintf("%v", customerID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/customers/%v", paramcustomerID)
}
