// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "customer": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/gostore/src/customer/design
// --out=$(GOPATH)/src/github.com/gostore/src/customer
// --version=v1.3.1

package test
